# Generated by Django 4.2.3 on 2023-08-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_anh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='anh',
            field=models.ImageField(blank=True, null=True, upload_to='pro_pic/'),
        ),
    ]
